spring:
  application:
    name: moviedb-graphql
  main:
    banner-mode: off
  datasource:
    url: ${JDBC_URL:jdbc:postgresql://localhost:5432/movies_db?rewriteBatchedStatements=true}
    username: ${JDBC_USER:postgres}
    password: ${JDBS_PSWD:admin}
    hikari:
      maximum-pool-size: ${JDBC_POOL_SIZE:4}
logging:
  level:
    Exposed: debug
