create table movies
(
    id             integer primary key generated by default as identity,
    title          text not null,
    original_title text not null,
    url            text,
    tagline        text,
    description    text not null,
    release_date   date,
    budged_usd     bigint,
    revenue_usd    bigint,
    rating         real,
    votes_count    integer
);

create table genres
(
    id   int primary key generated by default as identity,
    name text not null
);

create table tags
(
    id   int primary key generated by default as identity,
    name text not null
);

create table movie_tags
(
    movie_id int not null references movies,
    tag_id   int not null references tags,
    unique (movie_id, tag_id)
);


create table movie_genres
(
    movie_id int not null references movies,
    genre_id int not null references genres,
    unique (movie_id, genre_id)
);

