create table people
(
    id     int primary key generated by default as identity,
    name   text not null,
    gender text
);

create table movie_characters
(
    id               int primary key generated by default as identity,
    person_id        int references people,
    movie_id         int references movies,
    played_character text not null,
    priority_order   int  not null
);


create table movie_directors
(
    person_id int references people,
    movie_id  int references movies,
    unique (person_id, movie_id)
);


create table movie_composers
(
    person_id int references people,
    movie_id  int references movies,
    unique (person_id, movie_id)
);

